---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: portal
  name: acme-pv-claim
  labels:
    app: acme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
--- 