// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Delegation is the predicate function for delegation builders.
type Delegation func(*sql.Selector)

// Domain is the predicate function for domain builders.
type Domain func(*sql.Selector)
