// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Certificate is the predicate function for certificate builders.
type Certificate func(*sql.Selector)

// Domain is the predicate function for domain builders.
type Domain func(*sql.Selector)
