// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hm-edu/eab-rest-interface/ent/eabkey"
	"github.com/hm-edu/eab-rest-interface/ent/predicate"
)

// EABKeyQuery is the builder for querying EABKey entities.
type EABKeyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.EABKey
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EABKeyQuery builder.
func (ekq *EABKeyQuery) Where(ps ...predicate.EABKey) *EABKeyQuery {
	ekq.predicates = append(ekq.predicates, ps...)
	return ekq
}

// Limit adds a limit step to the query.
func (ekq *EABKeyQuery) Limit(limit int) *EABKeyQuery {
	ekq.limit = &limit
	return ekq
}

// Offset adds an offset step to the query.
func (ekq *EABKeyQuery) Offset(offset int) *EABKeyQuery {
	ekq.offset = &offset
	return ekq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ekq *EABKeyQuery) Unique(unique bool) *EABKeyQuery {
	ekq.unique = &unique
	return ekq
}

// Order adds an order step to the query.
func (ekq *EABKeyQuery) Order(o ...OrderFunc) *EABKeyQuery {
	ekq.order = append(ekq.order, o...)
	return ekq
}

// First returns the first EABKey entity from the query.
// Returns a *NotFoundError when no EABKey was found.
func (ekq *EABKeyQuery) First(ctx context.Context) (*EABKey, error) {
	nodes, err := ekq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{eabkey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ekq *EABKeyQuery) FirstX(ctx context.Context) *EABKey {
	node, err := ekq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EABKey ID from the query.
// Returns a *NotFoundError when no EABKey ID was found.
func (ekq *EABKeyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ekq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{eabkey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ekq *EABKeyQuery) FirstIDX(ctx context.Context) int {
	id, err := ekq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EABKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EABKey entity is found.
// Returns a *NotFoundError when no EABKey entities are found.
func (ekq *EABKeyQuery) Only(ctx context.Context) (*EABKey, error) {
	nodes, err := ekq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{eabkey.Label}
	default:
		return nil, &NotSingularError{eabkey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ekq *EABKeyQuery) OnlyX(ctx context.Context) *EABKey {
	node, err := ekq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EABKey ID in the query.
// Returns a *NotSingularError when more than one EABKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (ekq *EABKeyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ekq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{eabkey.Label}
	default:
		err = &NotSingularError{eabkey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ekq *EABKeyQuery) OnlyIDX(ctx context.Context) int {
	id, err := ekq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EABKeys.
func (ekq *EABKeyQuery) All(ctx context.Context) ([]*EABKey, error) {
	if err := ekq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ekq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ekq *EABKeyQuery) AllX(ctx context.Context) []*EABKey {
	nodes, err := ekq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EABKey IDs.
func (ekq *EABKeyQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ekq.Select(eabkey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ekq *EABKeyQuery) IDsX(ctx context.Context) []int {
	ids, err := ekq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ekq *EABKeyQuery) Count(ctx context.Context) (int, error) {
	if err := ekq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ekq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ekq *EABKeyQuery) CountX(ctx context.Context) int {
	count, err := ekq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ekq *EABKeyQuery) Exist(ctx context.Context) (bool, error) {
	if err := ekq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ekq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ekq *EABKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := ekq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EABKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ekq *EABKeyQuery) Clone() *EABKeyQuery {
	if ekq == nil {
		return nil
	}
	return &EABKeyQuery{
		config:     ekq.config,
		limit:      ekq.limit,
		offset:     ekq.offset,
		order:      append([]OrderFunc{}, ekq.order...),
		predicates: append([]predicate.EABKey{}, ekq.predicates...),
		// clone intermediate query.
		sql:    ekq.sql.Clone(),
		path:   ekq.path,
		unique: ekq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		User string `json:"user,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EABKey.Query().
//		GroupBy(eabkey.FieldUser).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ekq *EABKeyQuery) GroupBy(field string, fields ...string) *EABKeyGroupBy {
	grbuild := &EABKeyGroupBy{config: ekq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ekq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ekq.sqlQuery(ctx), nil
	}
	grbuild.label = eabkey.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		User string `json:"user,omitempty"`
//	}
//
//	client.EABKey.Query().
//		Select(eabkey.FieldUser).
//		Scan(ctx, &v)
func (ekq *EABKeyQuery) Select(fields ...string) *EABKeySelect {
	ekq.fields = append(ekq.fields, fields...)
	selbuild := &EABKeySelect{EABKeyQuery: ekq}
	selbuild.label = eabkey.Label
	selbuild.flds, selbuild.scan = &ekq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a EABKeySelect configured with the given aggregations.
func (ekq *EABKeyQuery) Aggregate(fns ...AggregateFunc) *EABKeySelect {
	return ekq.Select().Aggregate(fns...)
}

func (ekq *EABKeyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ekq.fields {
		if !eabkey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ekq.path != nil {
		prev, err := ekq.path(ctx)
		if err != nil {
			return err
		}
		ekq.sql = prev
	}
	return nil
}

func (ekq *EABKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EABKey, error) {
	var (
		nodes = []*EABKey{}
		_spec = ekq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EABKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EABKey{config: ekq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ekq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ekq *EABKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ekq.querySpec()
	_spec.Node.Columns = ekq.fields
	if len(ekq.fields) > 0 {
		_spec.Unique = ekq.unique != nil && *ekq.unique
	}
	return sqlgraph.CountNodes(ctx, ekq.driver, _spec)
}

func (ekq *EABKeyQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := ekq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (ekq *EABKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   eabkey.Table,
			Columns: eabkey.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: eabkey.FieldID,
			},
		},
		From:   ekq.sql,
		Unique: true,
	}
	if unique := ekq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ekq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eabkey.FieldID)
		for i := range fields {
			if fields[i] != eabkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ekq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ekq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ekq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ekq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ekq *EABKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ekq.driver.Dialect())
	t1 := builder.Table(eabkey.Table)
	columns := ekq.fields
	if len(columns) == 0 {
		columns = eabkey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ekq.sql != nil {
		selector = ekq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ekq.unique != nil && *ekq.unique {
		selector.Distinct()
	}
	for _, p := range ekq.predicates {
		p(selector)
	}
	for _, p := range ekq.order {
		p(selector)
	}
	if offset := ekq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ekq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EABKeyGroupBy is the group-by builder for EABKey entities.
type EABKeyGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ekgb *EABKeyGroupBy) Aggregate(fns ...AggregateFunc) *EABKeyGroupBy {
	ekgb.fns = append(ekgb.fns, fns...)
	return ekgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ekgb *EABKeyGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ekgb.path(ctx)
	if err != nil {
		return err
	}
	ekgb.sql = query
	return ekgb.sqlScan(ctx, v)
}

func (ekgb *EABKeyGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ekgb.fields {
		if !eabkey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ekgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ekgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ekgb *EABKeyGroupBy) sqlQuery() *sql.Selector {
	selector := ekgb.sql.Select()
	aggregation := make([]string, 0, len(ekgb.fns))
	for _, fn := range ekgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ekgb.fields)+len(ekgb.fns))
		for _, f := range ekgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ekgb.fields...)...)
}

// EABKeySelect is the builder for selecting fields of EABKey entities.
type EABKeySelect struct {
	*EABKeyQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eks *EABKeySelect) Aggregate(fns ...AggregateFunc) *EABKeySelect {
	eks.fns = append(eks.fns, fns...)
	return eks
}

// Scan applies the selector query and scans the result into the given value.
func (eks *EABKeySelect) Scan(ctx context.Context, v any) error {
	if err := eks.prepareQuery(ctx); err != nil {
		return err
	}
	eks.sql = eks.EABKeyQuery.sqlQuery(ctx)
	return eks.sqlScan(ctx, v)
}

func (eks *EABKeySelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(eks.fns))
	for _, fn := range eks.fns {
		aggregation = append(aggregation, fn(eks.sql))
	}
	switch n := len(*eks.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		eks.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		eks.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := eks.sql.Query()
	if err := eks.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
