// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hm-edu/eab-rest-interface/ent/eabkey"
	"github.com/hm-edu/eab-rest-interface/ent/predicate"
)

// EABKeyDelete is the builder for deleting a EABKey entity.
type EABKeyDelete struct {
	config
	hooks    []Hook
	mutation *EABKeyMutation
}

// Where appends a list predicates to the EABKeyDelete builder.
func (ekd *EABKeyDelete) Where(ps ...predicate.EABKey) *EABKeyDelete {
	ekd.mutation.Where(ps...)
	return ekd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ekd *EABKeyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ekd.hooks) == 0 {
		affected, err = ekd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EABKeyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ekd.mutation = mutation
			affected, err = ekd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ekd.hooks) - 1; i >= 0; i-- {
			if ekd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ekd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ekd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ekd *EABKeyDelete) ExecX(ctx context.Context) int {
	n, err := ekd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ekd *EABKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: eabkey.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: eabkey.FieldID,
			},
		},
	}
	if ps := ekd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ekd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// EABKeyDeleteOne is the builder for deleting a single EABKey entity.
type EABKeyDeleteOne struct {
	ekd *EABKeyDelete
}

// Exec executes the deletion query.
func (ekdo *EABKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := ekdo.ekd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eabkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ekdo *EABKeyDeleteOne) ExecX(ctx context.Context) {
	ekdo.ekd.ExecX(ctx)
}
