// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/hm-edu/pki-service/ent/certificate"
	"github.com/hm-edu/pki-service/ent/domain"
	"github.com/hm-edu/pki-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	certificateMixin := schema.Certificate{}.Mixin()
	certificateHooks := schema.Certificate{}.Hooks()
	certificate.Hooks[0] = certificateHooks[0]
	certificateMixinFields0 := certificateMixin[0].Fields()
	_ = certificateMixinFields0
	certificateFields := schema.Certificate{}.Fields()
	_ = certificateFields
	// certificateDescCreateTime is the schema descriptor for create_time field.
	certificateDescCreateTime := certificateMixinFields0[0].Descriptor()
	// certificate.DefaultCreateTime holds the default value on creation for the create_time field.
	certificate.DefaultCreateTime = certificateDescCreateTime.Default.(func() time.Time)
	// certificateDescUpdateTime is the schema descriptor for update_time field.
	certificateDescUpdateTime := certificateMixinFields0[1].Descriptor()
	// certificate.DefaultUpdateTime holds the default value on creation for the update_time field.
	certificate.DefaultUpdateTime = certificateDescUpdateTime.Default.(func() time.Time)
	// certificate.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	certificate.UpdateDefaultUpdateTime = certificateDescUpdateTime.UpdateDefault.(func() time.Time)
	// certificateDescCommonName is the schema descriptor for commonName field.
	certificateDescCommonName := certificateFields[3].Descriptor()
	// certificate.CommonNameValidator is a validator for the "commonName" field. It is called by the builders before save.
	certificate.CommonNameValidator = certificateDescCommonName.Validators[0].(func(string) error)
	domainFields := schema.Domain{}.Fields()
	_ = domainFields
	// domainDescFqdn is the schema descriptor for fqdn field.
	domainDescFqdn := domainFields[0].Descriptor()
	// domain.FqdnValidator is a validator for the "fqdn" field. It is called by the builders before save.
	domain.FqdnValidator = domainDescFqdn.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.1"                                         // Version of ent codegen.
	Sum     = "h1:fUERL506Pqr92EPHJqr8EYxbPioflJo6PudkrEA8a/s=" // Sum of ent codegen.
)
