name: Lint

concurrency:
  group: lint-${{ github.ref }}

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - backend/pki-rest-interface
          - backend/pki-service
          - backend/dns-service
          - backend/domain-rest-interface
          - backend/eab-rest-interface
          - backend/validation-service
          - backend/common
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
           working-directory: ${{ matrix.dir }}
           args: --timeout 240s
