name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - backend/pki-rest-interface
          - backend/pki-service
          - backend/dns-service
          - backend/domain-rest-interface
          - backend/eab-rest-interface
          - backend/validation-service
          - backend/common
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
        working-directory: ${{ matrix.dir }}
