name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: 
          - backend/pki-rest-interface
          - backend/pki-handler
          - backend/domain-rest-interface
          - backend/common
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
        working-directory: ${{ matrix.dir }}
