// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hm-edu/pki-service/ent/predicate"
	"github.com/hm-edu/pki-service/ent/smimecertificate"
)

// SmimeCertificateQuery is the builder for querying SmimeCertificate entities.
type SmimeCertificateQuery struct {
	config
	ctx        *QueryContext
	order      []smimecertificate.OrderOption
	inters     []Interceptor
	predicates []predicate.SmimeCertificate
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SmimeCertificateQuery builder.
func (scq *SmimeCertificateQuery) Where(ps ...predicate.SmimeCertificate) *SmimeCertificateQuery {
	scq.predicates = append(scq.predicates, ps...)
	return scq
}

// Limit the number of records to be returned by this query.
func (scq *SmimeCertificateQuery) Limit(limit int) *SmimeCertificateQuery {
	scq.ctx.Limit = &limit
	return scq
}

// Offset to start from.
func (scq *SmimeCertificateQuery) Offset(offset int) *SmimeCertificateQuery {
	scq.ctx.Offset = &offset
	return scq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scq *SmimeCertificateQuery) Unique(unique bool) *SmimeCertificateQuery {
	scq.ctx.Unique = &unique
	return scq
}

// Order specifies how the records should be ordered.
func (scq *SmimeCertificateQuery) Order(o ...smimecertificate.OrderOption) *SmimeCertificateQuery {
	scq.order = append(scq.order, o...)
	return scq
}

// First returns the first SmimeCertificate entity from the query.
// Returns a *NotFoundError when no SmimeCertificate was found.
func (scq *SmimeCertificateQuery) First(ctx context.Context) (*SmimeCertificate, error) {
	nodes, err := scq.Limit(1).All(setContextOp(ctx, scq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{smimecertificate.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scq *SmimeCertificateQuery) FirstX(ctx context.Context) *SmimeCertificate {
	node, err := scq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SmimeCertificate ID from the query.
// Returns a *NotFoundError when no SmimeCertificate ID was found.
func (scq *SmimeCertificateQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(1).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{smimecertificate.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scq *SmimeCertificateQuery) FirstIDX(ctx context.Context) int {
	id, err := scq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SmimeCertificate entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SmimeCertificate entity is found.
// Returns a *NotFoundError when no SmimeCertificate entities are found.
func (scq *SmimeCertificateQuery) Only(ctx context.Context) (*SmimeCertificate, error) {
	nodes, err := scq.Limit(2).All(setContextOp(ctx, scq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{smimecertificate.Label}
	default:
		return nil, &NotSingularError{smimecertificate.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scq *SmimeCertificateQuery) OnlyX(ctx context.Context) *SmimeCertificate {
	node, err := scq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SmimeCertificate ID in the query.
// Returns a *NotSingularError when more than one SmimeCertificate ID is found.
// Returns a *NotFoundError when no entities are found.
func (scq *SmimeCertificateQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = scq.Limit(2).IDs(setContextOp(ctx, scq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{smimecertificate.Label}
	default:
		err = &NotSingularError{smimecertificate.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scq *SmimeCertificateQuery) OnlyIDX(ctx context.Context) int {
	id, err := scq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SmimeCertificates.
func (scq *SmimeCertificateQuery) All(ctx context.Context) ([]*SmimeCertificate, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryAll)
	if err := scq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SmimeCertificate, *SmimeCertificateQuery]()
	return withInterceptors[[]*SmimeCertificate](ctx, scq, qr, scq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scq *SmimeCertificateQuery) AllX(ctx context.Context) []*SmimeCertificate {
	nodes, err := scq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SmimeCertificate IDs.
func (scq *SmimeCertificateQuery) IDs(ctx context.Context) (ids []int, err error) {
	if scq.ctx.Unique == nil && scq.path != nil {
		scq.Unique(true)
	}
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryIDs)
	if err = scq.Select(smimecertificate.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scq *SmimeCertificateQuery) IDsX(ctx context.Context) []int {
	ids, err := scq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scq *SmimeCertificateQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryCount)
	if err := scq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scq, querierCount[*SmimeCertificateQuery](), scq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scq *SmimeCertificateQuery) CountX(ctx context.Context) int {
	count, err := scq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scq *SmimeCertificateQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scq.ctx, ent.OpQueryExist)
	switch _, err := scq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scq *SmimeCertificateQuery) ExistX(ctx context.Context) bool {
	exist, err := scq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SmimeCertificateQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scq *SmimeCertificateQuery) Clone() *SmimeCertificateQuery {
	if scq == nil {
		return nil
	}
	return &SmimeCertificateQuery{
		config:     scq.config,
		ctx:        scq.ctx.Clone(),
		order:      append([]smimecertificate.OrderOption{}, scq.order...),
		inters:     append([]Interceptor{}, scq.inters...),
		predicates: append([]predicate.SmimeCertificate{}, scq.predicates...),
		// clone intermediate query.
		sql:  scq.sql.Clone(),
		path: scq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SmimeCertificate.Query().
//		GroupBy(smimecertificate.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scq *SmimeCertificateQuery) GroupBy(field string, fields ...string) *SmimeCertificateGroupBy {
	scq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SmimeCertificateGroupBy{build: scq}
	grbuild.flds = &scq.ctx.Fields
	grbuild.label = smimecertificate.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.SmimeCertificate.Query().
//		Select(smimecertificate.FieldCreateTime).
//		Scan(ctx, &v)
func (scq *SmimeCertificateQuery) Select(fields ...string) *SmimeCertificateSelect {
	scq.ctx.Fields = append(scq.ctx.Fields, fields...)
	sbuild := &SmimeCertificateSelect{SmimeCertificateQuery: scq}
	sbuild.label = smimecertificate.Label
	sbuild.flds, sbuild.scan = &scq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SmimeCertificateSelect configured with the given aggregations.
func (scq *SmimeCertificateQuery) Aggregate(fns ...AggregateFunc) *SmimeCertificateSelect {
	return scq.Select().Aggregate(fns...)
}

func (scq *SmimeCertificateQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scq); err != nil {
				return err
			}
		}
	}
	for _, f := range scq.ctx.Fields {
		if !smimecertificate.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scq.path != nil {
		prev, err := scq.path(ctx)
		if err != nil {
			return err
		}
		scq.sql = prev
	}
	return nil
}

func (scq *SmimeCertificateQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SmimeCertificate, error) {
	var (
		nodes = []*SmimeCertificate{}
		_spec = scq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SmimeCertificate).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SmimeCertificate{config: scq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (scq *SmimeCertificateQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scq.querySpec()
	_spec.Node.Columns = scq.ctx.Fields
	if len(scq.ctx.Fields) > 0 {
		_spec.Unique = scq.ctx.Unique != nil && *scq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scq.driver, _spec)
}

func (scq *SmimeCertificateQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(smimecertificate.Table, smimecertificate.Columns, sqlgraph.NewFieldSpec(smimecertificate.FieldID, field.TypeInt))
	_spec.From = scq.sql
	if unique := scq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scq.path != nil {
		_spec.Unique = true
	}
	if fields := scq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, smimecertificate.FieldID)
		for i := range fields {
			if fields[i] != smimecertificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := scq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scq *SmimeCertificateQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scq.driver.Dialect())
	t1 := builder.Table(smimecertificate.Table)
	columns := scq.ctx.Fields
	if len(columns) == 0 {
		columns = smimecertificate.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scq.sql != nil {
		selector = scq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scq.ctx.Unique != nil && *scq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scq.predicates {
		p(selector)
	}
	for _, p := range scq.order {
		p(selector)
	}
	if offset := scq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SmimeCertificateGroupBy is the group-by builder for SmimeCertificate entities.
type SmimeCertificateGroupBy struct {
	selector
	build *SmimeCertificateQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scgb *SmimeCertificateGroupBy) Aggregate(fns ...AggregateFunc) *SmimeCertificateGroupBy {
	scgb.fns = append(scgb.fns, fns...)
	return scgb
}

// Scan applies the selector query and scans the result into the given value.
func (scgb *SmimeCertificateGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scgb.build.ctx, ent.OpQueryGroupBy)
	if err := scgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SmimeCertificateQuery, *SmimeCertificateGroupBy](ctx, scgb.build, scgb, scgb.build.inters, v)
}

func (scgb *SmimeCertificateGroupBy) sqlScan(ctx context.Context, root *SmimeCertificateQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scgb.fns))
	for _, fn := range scgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scgb.flds)+len(scgb.fns))
		for _, f := range *scgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SmimeCertificateSelect is the builder for selecting fields of SmimeCertificate entities.
type SmimeCertificateSelect struct {
	*SmimeCertificateQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scs *SmimeCertificateSelect) Aggregate(fns ...AggregateFunc) *SmimeCertificateSelect {
	scs.fns = append(scs.fns, fns...)
	return scs
}

// Scan applies the selector query and scans the result into the given value.
func (scs *SmimeCertificateSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scs.ctx, ent.OpQuerySelect)
	if err := scs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SmimeCertificateQuery, *SmimeCertificateSelect](ctx, scs.SmimeCertificateQuery, scs, scs.inters, v)
}

func (scs *SmimeCertificateSelect) sqlScan(ctx context.Context, root *SmimeCertificateQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scs.fns))
	for _, fn := range scs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
